#!/bin/sh

. ~/badger/zclude

# mongo db
install "mongo db"

cd /tmp

sudo apt-key adv --keyserver keyserver.ubuntu.com --recv 7F0CEB10
sudo sh -c 'echo "deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen" | tee -a /etc/apt/sources.list.d/10gen.list'
sudo apt-get -y update
sudo apt-get -y install mongodb-10gen
sudo service mongodb start
