#!/bin/sh

. ~/badger/zclude

# unity themes
install "unity themes"

sudo add-apt-repository ppa:webupd8team/themes
sudo add-apt-repository ppa:tiheum/equinox
sudo apt-get update
sudo apt-get install zukitwo-theme
sudo apt-get install gnome-cupertino-gtk-theme

sudo apt-get install faenza-icon-theme
sudo apt-get install faience-icon-theme




